### ISSUE TITLE
sizeof(void*) + 1 bytes for char instead of 1

### ISSUE THREAD

**Issue by marcfedorow** [EdikGres/Lab-work-4#7]
https://github.com/EdikGres/Lab-work-4/blob/42b8e594523250973fa0f78e22498048c9fef272/Lab-work-4/MyLibForLab.cpp#L109

**Comment by EdikGres** [comment]
Thanks for the comment, the repository is old, there is no desire to update. Sorry.
YOU TOP BRO <3
